name: Bug Report
description: Report an error.
body:
  - type: textarea
    attributes:
      label: Description
      description: Please describe the error.
      placeholder: Details...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Recreation steps
      description: Please provide steps to recreate the error.
      placeholder: '1: ...'
